workflows:
  keepscore-ios:
    name: Keepscore iOS
    # See: https://docs.codemagic.io/getting-started/yaml/#cache
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods
    scripts:
      - name: iOS Build
        script: flutter build ios --debug --no-codesign

    # publishing:
    #   email:
    #     recipients:
    #       - hello@jesusoterogomez.com