// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN--IyWyTPTPgGhsPbGkmYo-1rYctubVA',
    appId: '1:582672140914:android:d1a977e5212c6052c090eb',
    messagingSenderId: '582672140914',
    projectId: 'getkeepscore',
    databaseURL: 'https://getkeepscore.firebaseio.com',
    storageBucket: 'getkeepscore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC1lHt0VKmz6eDQxhpvoNmfTIPTmMMLXs',
    appId: '1:582672140914:ios:12f0904633875fa8c090eb',
    messagingSenderId: '582672140914',
    projectId: 'getkeepscore',
    databaseURL: 'https://getkeepscore.firebaseio.com',
    storageBucket: 'getkeepscore.appspot.com',
    iosClientId:
        '582672140914-rk77f6g2dbdnmkllurpe7n9ut0o60j27.apps.googleusercontent.com',
    iosBundleId: 'com.example.next',
  );
}
